#define FIELDS \
    X(name,                              K_STR,    0,          CAT_ID) \
    X(uuid,                              K_BYTES,  0,          CAT_ID) \
    X(totalGlobalMem,                    K_SIZE,   fmt_bytes,  CAT_MEMORY) \
    X(sharedMemPerBlock,                 K_SIZE,   fmt_bytes,  CAT_MEMORY) \
    X(regsPerBlock,                      K_INT,    0,          CAT_COMPUTE) \
    X(warpSize,                          K_INT,    0,          CAT_COMPUTE) \
    X(memPitch,                          K_SIZE,   fmt_bytes,  CAT_MEMORY) \
    X(maxThreadsPerBlock,                K_INT,    0,          CAT_COMPUTE) \
    X(maxThreadsDim,                     K_IARR,   0,          CAT_COMPUTE) \
    X(maxGridSize,                       K_IARR,   0,          CAT_COMPUTE) \
    X(clockRate,                         K_INT,    fmt_clk,    CAT_COMPUTE) \
    X(totalConstMem,                     K_SIZE,   fmt_bytes,  CAT_MEMORY) \
    X(major,                             K_INT,    0,          CAT_COMPUTE) \
    X(minor,                             K_INT,    0,          CAT_COMPUTE) \
    X(textureAlignment,                  K_SIZE,   0,          CAT_TEXTURE) \
    X(texturePitchAlignment,             K_SIZE,   fmt_bytes,  CAT_TEXTURE) \
    X(deviceOverlap,                     K_INT,    0,          CAT_CAP) \
    X(multiProcessorCount,               K_INT,    0,          CAT_COMPUTE) \
    X(kernelExecTimeoutEnabled,          K_INT,    fmt_bool,   CAT_CAP) \
    X(integrated,                        K_INT,    fmt_bool,   CAT_CAP) \
    X(canMapHostMemory,                  K_INT,    fmt_bool,   CAT_MEMORY) \
    X(computeMode,                       K_INT,    0,          CAT_CAP) \
    X(maxTexture1D,                      K_INT,    0,          CAT_TEXTURE) \
    X(maxTexture1DMipmap,                K_INT,    0,          CAT_TEXTURE) \
    X(maxTexture1DLinear,                K_INT,    0,          CAT_TEXTURE) \
    X(maxTexture2D,                      K_IARR,   0,          CAT_TEXTURE) \
    X(maxTexture2DMipmap,                K_IARR,   0,          CAT_TEXTURE) \
    X(maxTexture2DLinear,                K_IARR,   0,          CAT_TEXTURE) \
    X(maxTexture2DGather,                K_IARR,   0,          CAT_TEXTURE) \
    X(maxTexture3D,                      K_IARR,   0,          CAT_TEXTURE) \
    X(maxTexture3DAlt,                   K_IARR,   0,          CAT_TEXTURE) \
    X(maxTextureCubemap,                 K_INT,    0,          CAT_TEXTURE) \
    X(maxTexture1DLayered,               K_IARR,   0,          CAT_TEXTURE) \
    X(maxTexture2DLayered,               K_IARR,   0,          CAT_TEXTURE) \
    X(maxTextureCubemapLayered,          K_IARR,   0,          CAT_TEXTURE) \
    X(maxSurface1D,                      K_INT,    0,          CAT_TEXTURE) \
    X(maxSurface2D,                      K_IARR,   0,          CAT_TEXTURE) \
    X(maxSurface3D,                      K_IARR,   0,          CAT_TEXTURE) \
    X(maxSurface1DLayered,               K_IARR,   0,          CAT_TEXTURE) \
    X(maxSurface2DLayered,               K_IARR,   0,          CAT_TEXTURE) \
    X(maxSurfaceCubemap,                 K_INT,    0,          CAT_TEXTURE) \
    X(maxSurfaceCubemapLayered,          K_IARR,   0,          CAT_TEXTURE) \
    X(surfaceAlignment,                  K_SIZE,   0,          CAT_TEXTURE) \
    X(concurrentKernels,                 K_INT,    fmt_bool,   CAT_CAP) \
    X(ECCEnabled,                        K_INT,    fmt_bool,   CAT_MEMORY) \
    X(pciBusID,                          K_INT,    0,          CAT_ID) \
    X(pciDeviceID,                       K_INT,    0,          CAT_ID) \
    X(pciDomainID,                       K_INT,    0,          CAT_ID) \
    X(tccDriver,                         K_INT,    0,          CAT_CAP) \
    X(asyncEngineCount,                  K_INT,    0,          CAT_CAP) \
    X(unifiedAddressing,                 K_INT,    fmt_bool,   CAT_CAP) \
    X(memoryClockRate,                   K_INT,    fmt_clk,    CAT_MEMORY) \
    X(memoryBusWidth,                    K_INT,    fmt_bits,   CAT_MEMORY) \
    X(l2CacheSize,                       K_INT,    fmt_bytes,  CAT_MEMORY) \
    X(persistingL2CacheMaxSize,          K_INT,    fmt_bytes,  CAT_MEMORY) \
    X(maxThreadsPerMultiProcessor,       K_INT,    0,          CAT_COMPUTE) \
    X(streamPrioritiesSupported,         K_INT,    fmt_bool,   CAT_CAP) \
    X(globalL1CacheSupported,            K_INT,    fmt_bool,   CAT_MEMORY) \
    X(localL1CacheSupported,             K_INT,    fmt_bool,   CAT_MEMORY) \
    X(sharedMemPerMultiprocessor,        K_SIZE,   fmt_bytes,  CAT_MEMORY) \
    X(regsPerMultiprocessor,             K_INT,    0,          CAT_COMPUTE) \
    X(managedMemory,                     K_INT,    fmt_bool,   CAT_MEMORY) \
    X(isMultiGpuBoard,                   K_INT,    fmt_bool,   CAT_ID) \
    X(multiGpuBoardGroupID,              K_INT,    0,          CAT_ID) \
    X(hostNativeAtomicSupported,         K_INT,    fmt_bool,   CAT_CAP) \
    X(singleToDoublePrecisionPerfRatio,  K_INT,    0,          CAT_CAP) \
    X(pageableMemoryAccess,              K_INT,    fmt_bool,   CAT_MEMORY) \
    X(concurrentManagedAccess,           K_INT,    fmt_bool,   CAT_CAP) \
    X(computePreemptionSupported,        K_INT,    fmt_bool,   CAT_CAP) \
    X(canUseHostPointerForRegisteredMem, K_INT,    fmt_bool,   CAT_MEMORY) \
    X(cooperativeLaunch,                 K_INT,    fmt_bool,   CAT_CAP) \
    X(cooperativeMultiDeviceLaunch,      K_INT,    fmt_bool,   CAT_CAP) \
    X(sharedMemPerBlockOptin,            K_SIZE,   fmt_bytes,  CAT_MEMORY) \
    X(pageableMemoryAccessUsesHostPageTables, K_INT,    fmt_bool ,  CAT_MEMORY) \
    X(directManagedMemAccessFromHost,    K_INT,    fmt_bool,   CAT_MEMORY) \
    X(maxBlocksPerMultiProcessor,        K_INT,    0,          CAT_COMPUTE) \
    X(accessPolicyMaxWindowSize,         K_INT,    0,          CAT_CAP) \
    X(reservedSharedMemPerBlock,         K_SIZE,   fmt_bytes,  CAT_MEMORY) \
    X(hostRegisterSupported,             K_INT,    fmt_bool,   CAT_CAP) \
    X(sparseCudaArraySupported,          K_INT,    fmt_bool,   CAT_CAP) \
    X(hostRegisterReadOnlySupported,     K_INT,    fmt_bool,   CAT_CAP) \
    X(timelineSemaphoreInteropSupported, K_INT,    fmt_bool,   CAT_CAP) \
    X(memoryPoolsSupported,              K_INT,    fmt_bool,   CAT_MEMORY) \
    X(gpuDirectRDMASupported,            K_INT,    fmt_bool,   CAT_CAP) \
    X(gpuDirectRDMAFlushWritesOptions,   K_UINT,   0,          CAT_CAP) \
    X(gpuDirectRDMAWritesOrdering,       K_INT,    0,          CAT_CAP) \
    X(memoryPoolSupportedHandleTypes,    K_UINT,   fmt_bool,   CAT_MEMORY) \
    X(deferredMappingCudaArraySupported, K_INT,    fmt_bool,   CAT_CAP) \
    X(ipcEventSupported,                 K_INT,    fmt_bool,   CAT_CAP) \
    X(clusterLaunch,                     K_INT,    0,          CAT_CAP) \
    X(unifiedFunctionPointers,           K_INT,    fmt_bool,   CAT_CAP) \
    /* end */
